// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelicviaShope;

#nullable disable

namespace RelicviaShope.Migrations;

[DbContext(typeof(DataBaseContext))]
[Migration("20250403121749_Migration2")]
partial class Migration2
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("RelicviaShope.Models.ShopingCard", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<int>("TovarId")
                    .HasColumnType("int");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("TovarId");

                b.HasIndex("UserId");

                b.ToTable("ShopingCards");
            });

        modelBuilder.Entity("RelicviaShope.Models.Tovar", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.ToTable("Tovars");
            });

        modelBuilder.Entity("RelicviaShope.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Discriminator")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("nvarchar(8)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Users");

                b.HasDiscriminator().HasValue("User");

                b.UseTphMappingStrategy();
            });

        modelBuilder.Entity("RelicviaShope.Models.Admin", b =>
            {
                b.HasBaseType("RelicviaShope.Models.User");

                b.HasDiscriminator().HasValue("Admin");
            });

        modelBuilder.Entity("RelicviaShope.Models.Trader", b =>
            {
                b.HasBaseType("RelicviaShope.Models.User");

                b.Property<string>("Inn")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasDiscriminator().HasValue("Trader");
            });

        modelBuilder.Entity("RelicviaShope.Models.ShopingCard", b =>
            {
                b.HasOne("RelicviaShope.Models.Tovar", "Tovar")
                    .WithMany("ShopingCards")
                    .HasForeignKey("TovarId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("RelicviaShope.Models.User", "User")
                    .WithMany("ShopingCards")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Tovar");

                b.Navigation("User");
            });

        modelBuilder.Entity("RelicviaShope.Models.Tovar", b =>
            {
                b.Navigation("ShopingCards");
            });

        modelBuilder.Entity("RelicviaShope.Models.User", b =>
            {
                b.Navigation("ShopingCards");
            });
#pragma warning restore 612, 618
    }
}
